### ISSUE TITLE
ERROR: Invalid interpolation format for "environment" option in service "skywalking-ui": "DAE_SEGMENT='^172\.19\.0.\d{1,3}$'"

### ISSUE THREAD

**Issue by li-xunhuan** [JaredTan95/skywalking-docker#11]
ERROR: Invalid interpolation format for "environment" option in service "skywalking-ui": "DAE_SEGMENT='^172\.19\.0.\d{1,3}$'"

**Comment by JaredTan95** [comment]
Can you provide your running command?

**Comment by li-xunhuan** [comment]
use https://github.com/JaredTan95/skywalking-docker/blob/master/5.x/quick-start/docker-compose.yml

**Comment by li-xunhuan** [comment]
嘻嘻……

**Comment by li-xunhuan** [comment]
啊……
这个问题有大佬回复一手吗？？？
