### ISSUE TITLE
能否弄个6.x的版本？

### ISSUE THREAD

**Issue by jueding920** [JaredTan95/skywalking-docker#16]
能否弄个6.x的版本？

**Comment by JaredTan95** [comment]
@jueding920  官方已经开始提供6.x版本的镜像。你可以先参考：https://github.com/apache/incubator-skywalking/blob/master/docker/README.md 和 kubenetes使用： https://github.com/apache/incubator-skywalking-kubernetes

**Comment by sxlstevengit** [comment]
官方的6.0镜像有500错误，怎么解决？

**Comment by JaredTan95** [comment]
> 官方的6.0镜像有500错误，怎么解决？

有报错日志吗？
