### ISSUE TITLE
quick start 'docker-compose' problem

### ISSUE THREAD

**Issue by wu-yafeng** [JaredTan95/skywalking-docker#17]
The quick start is not working.The skywalking container was exited after few seconds.

Ouput:

DCE-APP-ENTRY-POINT 2019/01/17 14:00:21 network: [ mac ], timeout: [ 20 ], failure: [ exit ], segment: [ '^192\.168\.12\.155' ]
DCE-APP-ENTRY-POINT 2019/01/17 14:00:21 try set env in MACVLAN network
DCE-APP-ENTRY-POINT 2019/01/17 14:00:21 find ip [ 127.0.0.1 ]
DCE-APP-ENTRY-POINT 2019/01/17 14:00:21 find ip [ 172.18.0.5 ]
DCE-APP-ENTRY-POINT 2019/01/17 14:00:26 try set env in MACVLAN network again
DCE-APP-ENTRY-POINT 2019/01/17 14:00:26 find ip [ 127.0.0.1 ]
DCE-APP-ENTRY-POINT 2019/01/17 14:00:26 find ip [ 172.18.0.5 ]
DCE-APP-ENTRY-POINT 2019/01/17 14:00:31 try set env in MACVLAN network again
DCE-APP-ENTRY-POINT 2019/01/17 14:00:31 find ip [ 127.0.0.1 ]
DCE-APP-ENTRY-POINT 2019/01/17 14:00:31 find ip [ 172.18.0.5 ]
DCE-APP-ENTRY-POINT 2019/01/17 14:00:36 try set env in MACVLAN network again
DCE-APP-ENTRY-POINT 2019/01/17 14:00:36 find ip [ 127.0.0.1 ]
DCE-APP-ENTRY-POINT 2019/01/17 14:00:36 find ip [ 172.18.0.5 ]
DCE-APP-ENTRY-POINT 2019/01/17 14:00:41 try set env in MACVLAN network again
DCE-APP-ENTRY-POINT 2019/01/17 14:00:41 timeout can't get macvlan ip...

**Comment by JaredTan95** [comment]
`DAE_SEGMENT ` env value should be set in regular expressions.
