### ISSUE TITLE
6.x Could not find or load main class org.apache.skywalking.oap.server.starter.OAPServerStartUp

### ISSUE THREAD

**Issue by jueding920** [JaredTan95/skywalking-docker#20]
6.x的docker-compose启动oap报错：
+ CLASSPATH=config:
+ CLASSPATH='oap-libs/*.jar:config:'
+ exec java -Xms512M -Xmx1024M -classpath 'oap-libs/*.jar:config:' org.apache.skywalking.oap.server.starter.OAPServerStartUp
Error: Could not find or load main class org.apache.skywalking.oap.server.starter.OAPServerStartUp
这个是为啥？

**Comment by w-a-n-g-s-h-u-n** [comment]
我也是

**Comment by zhoutaoo** [comment]
me too

**Comment by JaredTan95** [comment]
I will check recently.

**Comment by JaredTan95** [comment]
Hi, guys:
I fixed this issue and update to 6.1.0 version.

**Comment by WildWolfBang** [comment]
> Hi, guys:
> I fixed this issue and update to 6.1.0 version.

Can you explain the specific reason? I have encountered the build image running with the 6.4.0 version of the tar.gz package.

`+ exec java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms256M -classpath 'oap-libs/*.jar:config:' org.apache.skywalking.oap.server.starter.OAPServerStartUp
Error: Could not find or load main class org.apache.skywalking.oap.server.starter.OAPServerStartUp`
