### ISSUE TITLE
你好，是否能出个skywalking 8.1.0 es7 的docker部署

### ISSUE THREAD

**Issue by landonzeng** [JaredTan95/skywalking-docker#32]
rt，最近想使用skywalking8.1.0 es7的，但是配置的时候始终不报错：whitelabel error page，能否出个8.1.0 es7的，感谢！

**Comment by JaredTan95** [comment]
官方 apache/skywalking-docker https://github.com/apache/skywalking-docker/tree/master/8/8.1.0 仓库已经提供了哈
