### ISSUE TITLE
注册服务问题

### ISSUE THREAD

**Issue by ciweigg2** [JaredTan95/skywalking-docker#4]
你遇到过A服务器部署了skywalking B服务器部署java项目 B服务器无法注册服务到A上 提示连接不上GRPC么

**Comment by JaredTan95** [comment]
嗯，是不是网络不通？

**Comment by ciweigg2** [comment]
网络都通的，是不是本身就不能2个服务器，你测过这样的情况吗
一个服务器 注册和 起项目都ok的 2个就不行了

**Comment by JaredTan95** [comment]
你试试通过telnet ip port方式看看 10800 和11800两个端口绑定上了没。

**Comment by ciweigg2** [comment]
留个qq什么的吧 交流下 这个问题有点奇葩啊

**Comment by JaredTan95** [comment]
@ciweigg2  镜像更新了。WeChat：tj95ff,有什么疑问微信联系吧。
