### ISSUE TITLE
页面打开500错误

### ISSUE THREAD

**Issue by jianxuanbing** [JaredTan95/skywalking-docker#5]
使用`docker-compose.yml` 进行一键部署。但是打开页面一直都是提示 500

**Comment by JaredTan95** [comment]
可能是由于在使用docker-compose启动的时候，elastisearch还没完全启动，导致skywalking启动失败了。可以先尝试一下分开启动。

**Comment by jianxuanbing** [comment]
skywalking已经重新启动，但是还是依旧500
