### ISSUE TITLE
你好 部署问题

### ISSUE THREAD

**Issue by heli-boop** [JaredTan95/skywalking-docker#7]
生成docker镜像之后运行 /bin/sh: 1: /apache-skywalking-apm-incubating/bin/startupCollector.sh: not found

**Comment by JaredTan95** [comment]
@yunqianglee  it was the Dockerfile mischange.I just fixed it, and you can try it again.:P

**Comment by heli-boop** [comment]
shywalking 5.0-GA has not bin/startupCollector.sh, it has startup.sh

**Comment by JaredTan95** [comment]
Yep :p
